//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pracktice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sensors
    {
        public int id { get; set; }
        public byte[] LustReqested { get; set; }
        public Nullable<long> Interval { get; set; }
        public int ServerId { get; set; }
        public int SensorDataId { get; set; }
        public int Addres { get; set; }
        public int Type { get; set; }
        public int Transform { get; set; }
        public Nullable<double> IsEnabled { get; set; }
        public string Allias { get; set; }
    
        public virtual SensorsData SensorsData { get; set; }
        public virtual Servers Servers { get; set; }
    }
}
